import type { Metadata } from 'next'
import StyledComponentsRegistry from '@/libs/registry'
import './globals.css'
import { saira } from '@/fonts/fontConfig'
import Footer from '@/components/Desktop/DesktopFooter'
import AppProvider from '@/AppProvider'
import { headers } from 'next/headers'
import MobileFooter from '@/components/Mobile/MobileFooter'
import Header from '@/components/NewComponent/Header'

export const metadata: Metadata = {
  title: '캔버라커넥트',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = headers()
  const isMobilePredefined = headersList.get('x-is-mobile') === 'true'

  return (
    <html lang="ko">
      <body className={saira.className}>
        <StyledComponentsRegistry>
          <AppProvider>
            {isMobilePredefined ? (
              <>
                <Header />
                {children}
                <MobileFooter />
              </>
            ) : (
              <>
                <Header />
                {children}
                <Footer />
              </>
            )}
          </AppProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
